services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
      - ./pgbackup:/var/lib/postgresql/backup
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pw
      PYBOSSA_PASSWORD_FILE: /run/secrets/pybossa_pw
    restart: always
    secrets:
      - postgres_pw
      - pybossa_pw
    networks:
      - postgres-net
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    volumes:
      - ./config/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_pw
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    restart: always
    secrets:
      - pgadmin_pw
    networks:
      - postgres-net
    env_file:
      - ./config/pgadmin/.env

secrets:
  postgres_pw:
    file: ./config/secrets/postgres_pw.txt
  pybossa_pw:
    file: ./config/secrets/pybossa_pw.txt
  pgadmin_pw:
    file: ./config/secrets/pgadmin_pw.txt
   
networks:
  postgres-net:
    name: pybossa-postgres-net
