services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      .env
    restart: always
    networks:
      - backend
    

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    restart: always
    env_file:
      .env
    networks:
      - backend

networks:
  backend:
    name: pybossa-postgres-net
