#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$PYBOSSA_USER" WITH PASSWORD '"$PYBOSSA_PASSWORD"';
	CREATE DATABASE "$PYBOSSA_DB";
	GRANT ALL PRIVILEGES ON DATABASE "$PYBOSSA_DB" TO "$PYBOSSA_USER";
EOSQL
