#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username ${POSTGRES_USER} --dbname ${POSTGRES_DB} <<-EOSQL
	CREATE USER ${PYBOSSA_USER} WITH CREATEDB NOSUPERUSER PASSWORD '${PYBOSSA_PASSWORD}' ;
	CREATE DATABASE ${PYBOSSA_DB} WITH OWNER ${PYBOSSA_USER};
EOSQL
